dccp: Retire DCCP socket.
dccp_v4_protosw and inet6_dccp_ops.

DCCP socket is no longer supported.

  >>> from socket import *
  >>>
  >>> SOCK_DCCP = 6
  >>> s = socket(AF_INET, SOCK_DCCP)
  ...
  OSError: [Errno 94] Socket type not supported
  >>>
  >>> s = socket(AF_INET6, SOCK_DCCP)
  ...
  OSError: [Errno 94] Socket type not supported

No longer receive DCCP packets.

inet_del_protocol(&dccp_v4_protocol, IPPROTO_DCCP);
inet6_del_protocol(&dccp_v6_protocol, IPPROTO_DCCP)

Signed-off-by: Kuniyuki Iwashima <kuniyu@amazon.com>